import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../public/globals.css";
import { Box } from "@mui/material";
import Appbar from "@/components/Appbar";
import Appframe from "@/components/Appframe";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "App router",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Box>
          <Appframe children={children} />
        </Box>
      </body>
    </html>
  );
}
